name: agro

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_neumorphic: ^3.2.0
  loading_indicator: ^3.1.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_inset_box_shadow: ^1.0.8
  smooth_page_indicator: ^1.1.0
  dots_indicator: ^3.0.0
  custom_sliding_segmented_control: ^1.7.5
  pinput: ^2.2.31
  shrink_sidemenu: ^2.0.0+2-null-safety
  flutter_animation_progress_bar: ^2.3.1
  step_progress_indicator: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  mask_text_input_formatter: ^2.4.0
  transparent_image:
  image_picker: ^1.0.0
  flutter_rating_stars: ^1.0.3+4
  lottie: any
  share_plus: any
  fl_country_code_picker: ^0.1.5
  google_fonts: any
  fl_chart: any

  # PERSISTENCE
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

  # FIREBASE
  firebase_messaging: ^14.6.3
  firebase_core: ^2.14.0
  google_place: ^0.4.7

  # ARCHITECTURE
  provider: ^6.0.5
  path_provider: any

  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  local_auth: ^2.1.6

  # pay
  #  purchases_flutter: ^5.0.0
  #  rflutter_alert: ^2.0.7

  # SERVICE
  flutter_hooks: ^0.18.6
  responsive_framework: ^0.1.7
  flutter_localized_locales: ^2.0.4
  flutter_localizations:
    sdk: flutter
  pull_to_refresh: ^2.0.0
  helpers: ^1.2.3
  get: ^4.6.5
  in_app_notification: ^1.1.2
  clipboard: ^0.1.3

  # CONNECT
  url_launcher: ^6.1.11
  http: ^0.13.6
  intl: ^0.18.1


dev_dependencies:
  # PERSISTENCE
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  analyzer: ^5.13.0

  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - picture/
    - picture/start/
    - picture/auth/
    - picture/app/bottom_navigation/
    - picture/components/
    - picture/app/
    - picture/app/account/