name: agro

description: A new Flutter project.

publish_to: 'none'

version: 1.0.9+12

environment:
  sdk: '>=3.0.0-290.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_neumorphic: ^3.2.0
  loading_indicator: ^3.1.1
  modal_bottom_sheet: ^3.0.0-pre
  flutter_inset_box_shadow: ^1.0.8
  pinput: ^2.2.31
  mask_text_input_formatter: ^2.4.0
  flutter_rating_stars: ^1.0.3+4
  google_fonts: ^6.1.2
  # PERSISTENCE
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

  # FIREBASE
  firebase_core: 2.11.0
  firebase_messaging: 14.5.0
  #google_place: ^0.4.7

  # ARCHITECTURE
  provider: ^6.0.5

  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.7
  # pay
  #  purchases_flutter: ^5.0.0
  #  rflutter_alert: ^2.0.7

  # SERVICE
  flutter_hooks: ^0.18.6
  responsive_framework: ^0.1.7
  flutter_localizations:
    sdk: flutter
  pull_to_refresh: ^2.0.0
  get: ^4.6.5
  in_app_notification: ^1.1.2
  clipboard: ^0.1.3
  flutter_local_notifications: ^15.1.0+1
  permission_handler: ^11.0.1

  #bloc
  flutter_bloc: ^8.1.5
  bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^7.2.0

   #logger
  loggy: ^2.0.3

  # CONNECT
  url_launcher: ^6.1.11
  http: ^1.0.0
  intl: ^0.18.1


dev_dependencies:
  # PERSISTENCE
  build_runner: ^2.4.9
  flutter_lints: ^2.0.1
  analyzer: ^5.13.0
  dependency_validator: ^3.2.2

  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - picture/
    - picture/start/
    - picture/auth/
    - picture/app/bottom_navigation/
    - picture/components/
    - picture/app/
    - picture/app/account/